### ISSUE TITLE
Crash AnnA.py(1517)_compute_opti_rev_order() ro = -1 * (df.loc[due, "interval"].values +

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#20]
```
Computing relative overdueness...
NOTIF: This should probably not happen.
> /AnnA_Anki_neuronal_Appendix/AnnA.py(1517)_compute_opti_rev_order()
-> ro = -1 * (df.loc[due, "interval"].values +
(Pdb) bt
  /AnnA_Anki_neuronal_Appendix/autorun.py(19)<module>()
-> AnnA(deckname="/::s",
  /AnnA_Anki_neuronal_Appendix/AnnA.py(525)__init__()
-> self._compute_opti_rev_order()
> /AnnA_Anki_neuronal_Appendix/AnnA.py(1517)_compute_opti_rev_order()
-> ro = -1 * (df.loc[due, "interval"].values +
(Pdb)
```

**Comment by thiswillbeyourgithub** [comment]
Unfortunately this error code is part of the master branch and the current dev branch has changed too much for me to take the time to get into this.

My guess is that this is a specific issue that occured because of a specific arrangement of your review intervals and will probably not happen tomorow. I do remember encountering this once and this prompted me to change this part of the code.

Sorry for this, I still think the dev branch is stable enough for use! I'm considering merging them soon anyway.
