### ISSUE TITLE
Could you please make a YouTube video going through the setup of AnnA

### ISSUE THREAD

**Issue by jkPngu** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#21]
it would be quite useful

**Comment by thiswillbeyourgithub** [comment]
Hi,

Thanks for the interet but I really don't have time for this. Also, making it easier to install also means more maintenance as less experienced users get to try it.

In the end I believe AnnA should be ported as an addon with a GUI but won't deal with that until at least a year and a half so that's on hold.
