### ISSUE TITLE
Several notetypes match, wrong one selected

### ISSUE THREAD

**Issue by aleksejrs** [thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix#5]
```
Several notetypes match 'GEOG-country-flag'. Selecting 'GEOG-country'
Several notetypes match 'C-Bas-hidefrontFwd'. Selecting 'C-Bas'
Several notetypes match 'C-Clz-pron'. Selecting 'C-Clz'
```

Why? Those are all full names. Does it try fields from the correct matches too?

Anki 2.1.22 (I suppose it kind of works after some tweaking, but I am not sure, because it can't rebuild the filtered deck), AnnA commit e2c353e4112b7260b090dba950dd4a1bd9febb55.

**Comment by thiswillbeyourgithub** [comment]
Hi,

Indeed there was a bug, fixed in 7ddd9d6d15c13374dbe79ae5ef79acff5c18d50c + 5d74d65aef30fc040d7e39d79e108471b77aee7d, I don't have the time to test it today though, so if you could tell me if it works ok that would help :)

Thanks a lot!

I don't understand the issue you're running into to rebuild the deck, would you mind creating another issue with more explanation please?
